### ISSUE TITLE
AttributeError: unknown attribute: "weeks"   与“周”相关的日期不能正常解析

### ISSUE THREAD

**Issue by Beants** [fighting41love/cocoNLP#30]
代码如下
安装后没有更改任何代码，其他日期格式可以正常解析。只是与周相关的不能正常解析。
```python
text = '上周'
times = ex.extract_time(text)
print(times)
```
报错如下，请问如何解决，

```
Traceback (most recent call last):
  File "/Users/andersen/PycharmProjects/aminer/test.py", line 21, in <module>
    times = ex.extract_time(text)
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/cocoNLP/extractor.py", line 240, in extract_time
    res = tn.parse(target=tmp_text)  # target为待分析语句，timeBase为基准时间默认是当前时间
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/cocoNLP/config/basic/time_nlp/TimeNormalizer.py", line 94, in parse
    self.timeToken = self.__timeEx()
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/cocoNLP/config/basic/time_nlp/TimeNormalizer.py", line 169, in __timeEx
    res.append(TimeUnit(temp[i], self, contextTp))
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/cocoNLP/config/basic/time_nlp/TimeUnit.py", line 34, in __init__
    self.time_normalization()
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/cocoNLP/config/basic/time_nlp/TimeUnit.py", line 53, in time_normalization
    self.norm_setCurRelated()
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/cocoNLP/config/basic/time_nlp/TimeUnit.py", line 875, in norm_setCurRelated
    cur = cur.replace(weeks=-1, days=span)
  File "/Users/andersen/PycharmProjects/venv3.7.4/lib/python3.7/site-packages/arrow/arrow.py", line 612, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "weeks"
```

**Comment by rxy007** [comment]
这个是arrow库做了更新， 你把arrow库安装0.14.3这个版本就可以了， 其实是arrow废弃了一个方法， 改到了另外一个方法

**Comment by Beants** [comment]
> 这个是arrow库做了更新， 你把arrow库安装0.14.3这个版本就可以了， 其实是arrow废弃了一个方法， 改到了另外一个方法

**Comment by LHYintheCode** [comment]
thanks。Your advice is a great help to me.
