### ISSUE TITLE
pip install cocoNLP 有问题，在windows上安装，请问该怎么解决了

### ISSUE THREAD

**Issue by sunyh214** [fighting41love/cocoNLP#37]
(D:\Programs\python) C:\Users\sunyh>pip install cocoNLP
Collecting cocoNLP
  Using cached https://files.pythonhosted.org/packages/8f/c3/59aaa0fcaf7afb0853f0ce21570452f40048628f6b3cd68423ee3e798d05/cocoNLP-0.0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'arrow' (maybe misspelled?)
    No local packages or working download links found for arrow
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sunyh\AppData\Local\Temp\pip-build-i5gkisqz\cocoNLP\setup.py", line 75, in <module>
        cmdclass={'install': MyInstall},
      File "D:\Programs\python\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "D:\Programs\python\lib\site-packages\setuptools\dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "D:\Programs\python\lib\site-packages\setuptools\dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "D:\Programs\python\lib\site-packages\pkg_resources\__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "D:\Programs\python\lib\site-packages\pkg_resources\__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "D:\Programs\python\lib\site-packages\pkg_resources\__init__.py", line 1153, in obtain
        return installer(requirement)
      File "D:\Programs\python\lib\site-packages\setuptools\dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "D:\Programs\python\lib\site-packages\setuptools\command\easy_install.py", line 666, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('arrow')

**Comment by rookie-python** [comment]
jieba
pyhanlp
phone
phonenumbers
regex
arrow==0.14.3

你先 pip 把这些包都装包， 再安装cocoNLP， 不需要python3.6 ，我python3.9 也能用来
![image](https://user-images.githubusercontent.com/34366881/165214944-49380144-d5a5-4dc9-bc39-3092079be762.png)

**Comment by jing86736238** [comment]
> jieba pyhanlp phone phonenumbers regex arrow==0.14.3
> 
> 你先 pip 把这些包都装包， 再安装cocoNLP， 不需要python3.6 ，我python3.9 也能用来 ![image](https://user-images.githubusercontent.com/34366881/165214944-49380144-d5a5-4dc9-bc39-3092079be762.png)

但是你这里的话 是把arrow 包从1.几 降到了0.几， 我也不知道会有啥影响，可能用不到这个包
